// Generated by gencpp from file task_plan/traj_out_msg.msg
// DO NOT EDIT!


#ifndef TASK_PLAN_MESSAGE_TRAJ_OUT_MSG_H
#define TASK_PLAN_MESSAGE_TRAJ_OUT_MSG_H

#include <ros/service_traits.h>


#include <task_plan/traj_out_msgRequest.h>
#include <task_plan/traj_out_msgResponse.h>


namespace task_plan
{

struct traj_out_msg
{

typedef traj_out_msgRequest Request;
typedef traj_out_msgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct traj_out_msg
} // namespace task_plan


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task_plan::traj_out_msg > {
  static const char* value()
  {
    return "d5e5f46daf7567dab08610da48ae237e";
  }

  static const char* value(const ::task_plan::traj_out_msg&) { return value(); }
};

template<>
struct DataType< ::task_plan::traj_out_msg > {
  static const char* value()
  {
    return "task_plan/traj_out_msg";
  }

  static const char* value(const ::task_plan::traj_out_msg&) { return value(); }
};


// service_traits::MD5Sum< ::task_plan::traj_out_msgRequest> should match
// service_traits::MD5Sum< ::task_plan::traj_out_msg >
template<>
struct MD5Sum< ::task_plan::traj_out_msgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task_plan::traj_out_msg >::value();
  }
  static const char* value(const ::task_plan::traj_out_msgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task_plan::traj_out_msgRequest> should match
// service_traits::DataType< ::task_plan::traj_out_msg >
template<>
struct DataType< ::task_plan::traj_out_msgRequest>
{
  static const char* value()
  {
    return DataType< ::task_plan::traj_out_msg >::value();
  }
  static const char* value(const ::task_plan::traj_out_msgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task_plan::traj_out_msgResponse> should match
// service_traits::MD5Sum< ::task_plan::traj_out_msg >
template<>
struct MD5Sum< ::task_plan::traj_out_msgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task_plan::traj_out_msg >::value();
  }
  static const char* value(const ::task_plan::traj_out_msgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task_plan::traj_out_msgResponse> should match
// service_traits::DataType< ::task_plan::traj_out_msg >
template<>
struct DataType< ::task_plan::traj_out_msgResponse>
{
  static const char* value()
  {
    return DataType< ::task_plan::traj_out_msg >::value();
  }
  static const char* value(const ::task_plan::traj_out_msgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK_PLAN_MESSAGE_TRAJ_OUT_MSG_H
