// Generated by gencpp from file navigator/interface.msg
// DO NOT EDIT!


#ifndef NAVIGATOR_MESSAGE_INTERFACE_H
#define NAVIGATOR_MESSAGE_INTERFACE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace navigator
{
template <class ContainerAllocator>
struct interface_
{
  typedef interface_<ContainerAllocator> Type;

  interface_()
    : header()
    , behavior(0)
    , behaviormode(0)
    , params(0.0)  {
    }
  interface_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , behavior(0)
    , behaviormode(0)
    , params(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _behavior_type;
  _behavior_type behavior;

   typedef uint8_t _behaviormode_type;
  _behaviormode_type behaviormode;

   typedef double _params_type;
  _params_type params;





  typedef boost::shared_ptr< ::navigator::interface_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigator::interface_<ContainerAllocator> const> ConstPtr;

}; // struct interface_

typedef ::navigator::interface_<std::allocator<void> > interface;

typedef boost::shared_ptr< ::navigator::interface > interfacePtr;
typedef boost::shared_ptr< ::navigator::interface const> interfaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigator::interface_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigator::interface_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigator::interface_<ContainerAllocator1> & lhs, const ::navigator::interface_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.behavior == rhs.behavior &&
    lhs.behaviormode == rhs.behaviormode &&
    lhs.params == rhs.params;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigator::interface_<ContainerAllocator1> & lhs, const ::navigator::interface_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::navigator::interface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigator::interface_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigator::interface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigator::interface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigator::interface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigator::interface_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigator::interface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dae9a4e6d7acf972163a081d07c9c96d";
  }

  static const char* value(const ::navigator::interface_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdae9a4e6d7acf972ULL;
  static const uint64_t static_value2 = 0x163a081d07c9c96dULL;
};

template<class ContainerAllocator>
struct DataType< ::navigator::interface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigator/interface";
  }

  static const char* value(const ::navigator::interface_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigator::interface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#(1) waypoint flight: x,y,z,yaw in ENU frame\n"
"\n"
"Header header\n"
"uint8  behavior\n"
"uint8  behaviormode\n"
"float64 params\n"
"#geometry_msgs/PoseStamped[] uav_waypoint\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::navigator::interface_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigator::interface_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.behavior);
      stream.next(m.behaviormode);
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct interface_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigator::interface_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigator::interface_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "behavior: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.behavior);
    s << indent << "behaviormode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.behaviormode);
    s << indent << "params: ";
    Printer<double>::stream(s, indent + "  ", v.params);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATOR_MESSAGE_INTERFACE_H
