// Generated by gencpp from file clik/traj_solver_msgResponse.msg
// DO NOT EDIT!


#ifndef CLIK_MESSAGE_TRAJ_SOLVER_MSGRESPONSE_H
#define CLIK_MESSAGE_TRAJ_SOLVER_MSGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clik
{
template <class ContainerAllocator>
struct traj_solver_msgResponse_
{
  typedef traj_solver_msgResponse_<ContainerAllocator> Type;

  traj_solver_msgResponse_()
    : resultstatus(false)  {
    }
  traj_solver_msgResponse_(const ContainerAllocator& _alloc)
    : resultstatus(false)  {
  (void)_alloc;
    }



   typedef uint8_t _resultstatus_type;
  _resultstatus_type resultstatus;





  typedef boost::shared_ptr< ::clik::traj_solver_msgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clik::traj_solver_msgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct traj_solver_msgResponse_

typedef ::clik::traj_solver_msgResponse_<std::allocator<void> > traj_solver_msgResponse;

typedef boost::shared_ptr< ::clik::traj_solver_msgResponse > traj_solver_msgResponsePtr;
typedef boost::shared_ptr< ::clik::traj_solver_msgResponse const> traj_solver_msgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clik::traj_solver_msgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clik::traj_solver_msgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clik::traj_solver_msgResponse_<ContainerAllocator1> & lhs, const ::clik::traj_solver_msgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.resultstatus == rhs.resultstatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clik::traj_solver_msgResponse_<ContainerAllocator1> & lhs, const ::clik::traj_solver_msgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clik

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::clik::traj_solver_msgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clik::traj_solver_msgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clik::traj_solver_msgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clik::traj_solver_msgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clik::traj_solver_msgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clik::traj_solver_msgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clik::traj_solver_msgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02a1365fbb049f415398ed38aa76782f";
  }

  static const char* value(const ::clik::traj_solver_msgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02a1365fbb049f41ULL;
  static const uint64_t static_value2 = 0x5398ed38aa76782fULL;
};

template<class ContainerAllocator>
struct DataType< ::clik::traj_solver_msgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clik/traj_solver_msgResponse";
  }

  static const char* value(const ::clik::traj_solver_msgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clik::traj_solver_msgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool resultstatus\n"
;
  }

  static const char* value(const ::clik::traj_solver_msgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clik::traj_solver_msgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resultstatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct traj_solver_msgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clik::traj_solver_msgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clik::traj_solver_msgResponse_<ContainerAllocator>& v)
  {
    s << indent << "resultstatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.resultstatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLIK_MESSAGE_TRAJ_SOLVER_MSGRESPONSE_H
