// Generated by gencpp from file clik/traj_solver_msg.msg
// DO NOT EDIT!


#ifndef CLIK_MESSAGE_TRAJ_SOLVER_MSG_H
#define CLIK_MESSAGE_TRAJ_SOLVER_MSG_H

#include <ros/service_traits.h>


#include <clik/traj_solver_msgRequest.h>
#include <clik/traj_solver_msgResponse.h>


namespace clik
{

struct traj_solver_msg
{

typedef traj_solver_msgRequest Request;
typedef traj_solver_msgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct traj_solver_msg
} // namespace clik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clik::traj_solver_msg > {
  static const char* value()
  {
    return "38d31568563b236264303ee6e91f80dd";
  }

  static const char* value(const ::clik::traj_solver_msg&) { return value(); }
};

template<>
struct DataType< ::clik::traj_solver_msg > {
  static const char* value()
  {
    return "clik/traj_solver_msg";
  }

  static const char* value(const ::clik::traj_solver_msg&) { return value(); }
};


// service_traits::MD5Sum< ::clik::traj_solver_msgRequest> should match
// service_traits::MD5Sum< ::clik::traj_solver_msg >
template<>
struct MD5Sum< ::clik::traj_solver_msgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clik::traj_solver_msg >::value();
  }
  static const char* value(const ::clik::traj_solver_msgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clik::traj_solver_msgRequest> should match
// service_traits::DataType< ::clik::traj_solver_msg >
template<>
struct DataType< ::clik::traj_solver_msgRequest>
{
  static const char* value()
  {
    return DataType< ::clik::traj_solver_msg >::value();
  }
  static const char* value(const ::clik::traj_solver_msgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clik::traj_solver_msgResponse> should match
// service_traits::MD5Sum< ::clik::traj_solver_msg >
template<>
struct MD5Sum< ::clik::traj_solver_msgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clik::traj_solver_msg >::value();
  }
  static const char* value(const ::clik::traj_solver_msgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clik::traj_solver_msgResponse> should match
// service_traits::DataType< ::clik::traj_solver_msg >
template<>
struct DataType< ::clik::traj_solver_msgResponse>
{
  static const char* value()
  {
    return DataType< ::clik::traj_solver_msg >::value();
  }
  static const char* value(const ::clik::traj_solver_msgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLIK_MESSAGE_TRAJ_SOLVER_MSG_H
