// Generated by gencpp from file clik/traj_out_msg.msg
// DO NOT EDIT!


#ifndef CLIK_MESSAGE_TRAJ_OUT_MSG_H
#define CLIK_MESSAGE_TRAJ_OUT_MSG_H

#include <ros/service_traits.h>


#include <clik/traj_out_msgRequest.h>
#include <clik/traj_out_msgResponse.h>


namespace clik
{

struct traj_out_msg
{

typedef traj_out_msgRequest Request;
typedef traj_out_msgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct traj_out_msg
} // namespace clik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clik::traj_out_msg > {
  static const char* value()
  {
    return "d5e5f46daf7567dab08610da48ae237e";
  }

  static const char* value(const ::clik::traj_out_msg&) { return value(); }
};

template<>
struct DataType< ::clik::traj_out_msg > {
  static const char* value()
  {
    return "clik/traj_out_msg";
  }

  static const char* value(const ::clik::traj_out_msg&) { return value(); }
};


// service_traits::MD5Sum< ::clik::traj_out_msgRequest> should match
// service_traits::MD5Sum< ::clik::traj_out_msg >
template<>
struct MD5Sum< ::clik::traj_out_msgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clik::traj_out_msg >::value();
  }
  static const char* value(const ::clik::traj_out_msgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clik::traj_out_msgRequest> should match
// service_traits::DataType< ::clik::traj_out_msg >
template<>
struct DataType< ::clik::traj_out_msgRequest>
{
  static const char* value()
  {
    return DataType< ::clik::traj_out_msg >::value();
  }
  static const char* value(const ::clik::traj_out_msgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clik::traj_out_msgResponse> should match
// service_traits::MD5Sum< ::clik::traj_out_msg >
template<>
struct MD5Sum< ::clik::traj_out_msgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clik::traj_out_msg >::value();
  }
  static const char* value(const ::clik::traj_out_msgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clik::traj_out_msgResponse> should match
// service_traits::DataType< ::clik::traj_out_msg >
template<>
struct DataType< ::clik::traj_out_msgResponse>
{
  static const char* value()
  {
    return DataType< ::clik::traj_out_msg >::value();
  }
  static const char* value(const ::clik::traj_out_msgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLIK_MESSAGE_TRAJ_OUT_MSG_H
