(cl:defpackage clik-srv
  (:use )
  (:export
   "MANIPULATOR_MODE"
   "<MANIPULATOR_MODE-REQUEST>"
   "MANIPULATOR_MODE-REQUEST"
   "<MANIPULATOR_MODE-RESPONSE>"
   "MANIPULATOR_MODE-RESPONSE"
   "TRAJ_OUT_MSG"
   "<TRAJ_OUT_MSG-REQUEST>"
   "TRAJ_OUT_MSG-REQUEST"
   "<TRAJ_OUT_MSG-RESPONSE>"
   "TRAJ_OUT_MSG-RESPONSE"
   "TRAJ_SOLVER_MSG"
   "<TRAJ_SOLVER_MSG-REQUEST>"
   "TRAJ_SOLVER_MSG-REQUEST"
   "<TRAJ_SOLVER_MSG-RESPONSE>"
   "TRAJ_SOLVER_MSG-RESPONSE"
  ))

