(cl:in-package clik-srv)
(cl:export '(S_SCALE-VAL
          S_SCALE
          X_UPPERPOSITION-VAL
          X_UPPERPOSITION
          X_LOWERPOSITION-VAL
          X_LOWERPOSITION
          X_UPPERVELOCITY-VAL
          X_UPPERVELOCITY
          X_LOWERVELOCITY-VAL
          X_LOWERVELOCITY
          X_UPPERACCELERA-VAL
          X_UPPERACCELERA
          X_LOWERACCELERA-VAL
          X_LOWERACCELERA
          X_0-VAL
          X_0
          X_N-VAL
          X_N
          X_V0-VAL
          X_V0
          X_VN-VAL
          X_VN
          Y_UPPERPOSITION-VAL
          Y_UPPERPOSITION
          Y_LOWERPOSITION-VAL
          Y_LOWERPOSITION
          Y_UPPERVELOCITY-VAL
          Y_UPPERVELOCITY
          Y_LOWERVELOCITY-VAL
          Y_LOWERVELOCITY
          Y_UPPERACCELERA-VAL
          Y_UPPERACCELERA
          Y_LOWERACCELERA-VAL
          Y_LOWERACCELERA
          Y_0-VAL
          Y_0
          Y_N-VAL
          Y_N
          Y_V0-VAL
          Y_V0
          Y_VN-VAL
          Y_VN
          Z_UPPERPOSITION-VAL
          Z_UPPERPOSITION
          Z_LOWERPOSITION-VAL
          Z_LOWERPOSITION
          Z_UPPERVELOCITY-VAL
          Z_UPPERVELOCITY
          Z_LOWERVELOCITY-VAL
          Z_LOWERVELOCITY
          Z_UPPERACCELERA-VAL
          Z_UPPERACCELERA
          Z_LOWERACCELERA-VAL
          Z_LOWERACCELERA
          Z_0-VAL
          Z_0
          Z_N-VAL
          Z_N
          Z_V0-VAL
          Z_V0
          Z_VN-VAL
          Z_VN
          RESULTSTATUS-VAL
          RESULTSTATUS
))