// Generated by gencpp from file calibration/manipulator_mode.msg
// DO NOT EDIT!


#ifndef CALIBRATION_MESSAGE_MANIPULATOR_MODE_H
#define CALIBRATION_MESSAGE_MANIPULATOR_MODE_H

#include <ros/service_traits.h>


#include <calibration/manipulator_modeRequest.h>
#include <calibration/manipulator_modeResponse.h>


namespace calibration
{

struct manipulator_mode
{

typedef manipulator_modeRequest Request;
typedef manipulator_modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct manipulator_mode
} // namespace calibration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::calibration::manipulator_mode > {
  static const char* value()
  {
    return "824ed9c4ea0b3e2aae8eb76e8fc86e2c";
  }

  static const char* value(const ::calibration::manipulator_mode&) { return value(); }
};

template<>
struct DataType< ::calibration::manipulator_mode > {
  static const char* value()
  {
    return "calibration/manipulator_mode";
  }

  static const char* value(const ::calibration::manipulator_mode&) { return value(); }
};


// service_traits::MD5Sum< ::calibration::manipulator_modeRequest> should match
// service_traits::MD5Sum< ::calibration::manipulator_mode >
template<>
struct MD5Sum< ::calibration::manipulator_modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::calibration::manipulator_mode >::value();
  }
  static const char* value(const ::calibration::manipulator_modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::calibration::manipulator_modeRequest> should match
// service_traits::DataType< ::calibration::manipulator_mode >
template<>
struct DataType< ::calibration::manipulator_modeRequest>
{
  static const char* value()
  {
    return DataType< ::calibration::manipulator_mode >::value();
  }
  static const char* value(const ::calibration::manipulator_modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::calibration::manipulator_modeResponse> should match
// service_traits::MD5Sum< ::calibration::manipulator_mode >
template<>
struct MD5Sum< ::calibration::manipulator_modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::calibration::manipulator_mode >::value();
  }
  static const char* value(const ::calibration::manipulator_modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::calibration::manipulator_modeResponse> should match
// service_traits::DataType< ::calibration::manipulator_mode >
template<>
struct DataType< ::calibration::manipulator_modeResponse>
{
  static const char* value()
  {
    return DataType< ::calibration::manipulator_mode >::value();
  }
  static const char* value(const ::calibration::manipulator_modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CALIBRATION_MESSAGE_MANIPULATOR_MODE_H
