// Generated by gencpp from file calibration/manipulator_modeRequest.msg
// DO NOT EDIT!


#ifndef CALIBRATION_MESSAGE_MANIPULATOR_MODEREQUEST_H
#define CALIBRATION_MESSAGE_MANIPULATOR_MODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace calibration
{
template <class ContainerAllocator>
struct manipulator_modeRequest_
{
  typedef manipulator_modeRequest_<ContainerAllocator> Type;

  manipulator_modeRequest_()
    : mode(0)  {
    }
  manipulator_modeRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef int64_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::calibration::manipulator_modeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::calibration::manipulator_modeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct manipulator_modeRequest_

typedef ::calibration::manipulator_modeRequest_<std::allocator<void> > manipulator_modeRequest;

typedef boost::shared_ptr< ::calibration::manipulator_modeRequest > manipulator_modeRequestPtr;
typedef boost::shared_ptr< ::calibration::manipulator_modeRequest const> manipulator_modeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::calibration::manipulator_modeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::calibration::manipulator_modeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::calibration::manipulator_modeRequest_<ContainerAllocator1> & lhs, const ::calibration::manipulator_modeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::calibration::manipulator_modeRequest_<ContainerAllocator1> & lhs, const ::calibration::manipulator_modeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace calibration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::calibration::manipulator_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calibration::manipulator_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calibration::manipulator_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calibration::manipulator_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration::manipulator_modeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration::manipulator_modeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::calibration::manipulator_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "284404659b502753974e60f7457ed2dc";
  }

  static const char* value(const ::calibration::manipulator_modeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x284404659b502753ULL;
  static const uint64_t static_value2 = 0x974e60f7457ed2dcULL;
};

template<class ContainerAllocator>
struct DataType< ::calibration::manipulator_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calibration/manipulator_modeRequest";
  }

  static const char* value(const ::calibration::manipulator_modeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::calibration::manipulator_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 mode\n"
;
  }

  static const char* value(const ::calibration::manipulator_modeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::calibration::manipulator_modeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct manipulator_modeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::calibration::manipulator_modeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::calibration::manipulator_modeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CALIBRATION_MESSAGE_MANIPULATOR_MODEREQUEST_H
