// Generated by gencpp from file sim2real/cmd_mode.msg
// DO NOT EDIT!


#ifndef SIM2REAL_MESSAGE_CMD_MODE_H
#define SIM2REAL_MESSAGE_CMD_MODE_H

#include <ros/service_traits.h>


#include <sim2real/cmd_modeRequest.h>
#include <sim2real/cmd_modeResponse.h>


namespace sim2real
{

struct cmd_mode
{

typedef cmd_modeRequest Request;
typedef cmd_modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cmd_mode
} // namespace sim2real


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sim2real::cmd_mode > {
  static const char* value()
  {
    return "824ed9c4ea0b3e2aae8eb76e8fc86e2c";
  }

  static const char* value(const ::sim2real::cmd_mode&) { return value(); }
};

template<>
struct DataType< ::sim2real::cmd_mode > {
  static const char* value()
  {
    return "sim2real/cmd_mode";
  }

  static const char* value(const ::sim2real::cmd_mode&) { return value(); }
};


// service_traits::MD5Sum< ::sim2real::cmd_modeRequest> should match
// service_traits::MD5Sum< ::sim2real::cmd_mode >
template<>
struct MD5Sum< ::sim2real::cmd_modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sim2real::cmd_mode >::value();
  }
  static const char* value(const ::sim2real::cmd_modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim2real::cmd_modeRequest> should match
// service_traits::DataType< ::sim2real::cmd_mode >
template<>
struct DataType< ::sim2real::cmd_modeRequest>
{
  static const char* value()
  {
    return DataType< ::sim2real::cmd_mode >::value();
  }
  static const char* value(const ::sim2real::cmd_modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sim2real::cmd_modeResponse> should match
// service_traits::MD5Sum< ::sim2real::cmd_mode >
template<>
struct MD5Sum< ::sim2real::cmd_modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sim2real::cmd_mode >::value();
  }
  static const char* value(const ::sim2real::cmd_modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim2real::cmd_modeResponse> should match
// service_traits::DataType< ::sim2real::cmd_mode >
template<>
struct DataType< ::sim2real::cmd_modeResponse>
{
  static const char* value()
  {
    return DataType< ::sim2real::cmd_mode >::value();
  }
  static const char* value(const ::sim2real::cmd_modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIM2REAL_MESSAGE_CMD_MODE_H
